using codewars.Katas;
//Console.WriteLine();
//KataRankUp6.Orders("the2 Fo1r 4of th5e pe6ople g3ood");
//Console.WriteLine(convertStringToCamelCase.ToCamelCase("the_stealth_warrior"));
//Console.WriteLine(shortestWord.FindShort("Let's travel abroad shall we"));
//Console.WriteLine(RgbToHex.Rgb(148,0,211));
//Console.WriteLine(weight.orderWeight("2000 10003 1234000 44444444 9999 11 11 22 123"));
//Console.WriteLine(smileys.CountSmileys(new string[]{":D", ":~)", ";~D", ":)"}));
//Console.WriteLine(missingLetter.FindMissingLetter(new char[]{'O','Q','R','S'}));
//Console.WriteLine(unluckyDays.UnluckyDays(2723));
//Console.WriteLine(panagram.IsPangram("ABCD45EFGH,IJK,LMNOPQR56STUVW3XYZ"));
//Console.WriteLine(ulongs.Digits(9876543210ul));
//Console.WriteLine(merged.isMerge("banana", "banan", "aa"));
//Console.WriteLine(disctinctNumbers.Solve(new List<int>{-9,-105,-9,-9,-9,-9,105}));
Console.WriteLine(reversed.solve("code wars"));